// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemCri.Infrastructure.Data;

#nullable disable

namespace SystemCri.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260607031500_InitialCreate_Municipios")]
    partial class InitialCreate_Municipios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemCri.Domain.Entities.Depto", b =>
                {
                    b.Property<int>("DeptoCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptoCod"));

                    b.Property<string>("DeptoDescrip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeptoNom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptoCod");

                    b.ToTable("Deptos");
                });

            modelBuilder.Entity("SystemCri.Domain.Entities.Municipio", b =>
                {
                    b.Property<int>("MunicipioCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MunicipioCod"));

                    b.Property<int?>("DeptoCod")
                        .HasColumnType("int");

                    b.Property<string>("MunicipioNom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MunicipioCod");

                    b.HasIndex("DeptoCod");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("SystemCri.Domain.Entities.Municipio", b =>
                {
                    b.HasOne("SystemCri.Domain.Entities.Depto", "Depto")
                        .WithMany()
                        .HasForeignKey("DeptoCod")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Depto");
                });
#pragma warning restore 612, 618
        }
    }
}
