// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemCri.Infrastructure.Data;

#nullable disable

namespace SystemCri.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260609181639_AddAcceso")]
    partial class AddAcceso
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemCri.Domain.Entities.Acceso", b =>
                {
                    b.Property<int>("CodAcceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodAcceso"));

                    b.Property<DateTime>("FechaFAcceso")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaIAcceso")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("CodAcceso");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Accesos");
                });

            modelBuilder.Entity("SystemCri.Domain.Entities.Depto", b =>
                {
                    b.Property<int>("DeptoCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptoCod"));

                    b.Property<string>("DeptoDescrip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeptoNom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptoCod");

                    b.ToTable("Deptos");
                });

            modelBuilder.Entity("SystemCri.Domain.Entities.Municipio", b =>
                {
                    b.Property<int>("MunicipioCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MunicipioCod"));

                    b.Property<int?>("DeptoCod")
                        .HasColumnType("int");

                    b.Property<string>("MunicipioNom")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MunicipioCod");

                    b.HasIndex("DeptoCod");

                    b.ToTable("Municipios");
                });

            modelBuilder.Entity("SystemCri.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<int?>("UsuarioDepartamento")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioDescripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioEstado")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioEtnia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("UsuarioLogo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("UsuarioMunicipio")
                        .HasColumnType("int");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("UsuarioPie")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("UsuarioId");

                    b.HasIndex("UsuarioDepartamento");

                    b.HasIndex("UsuarioMunicipio");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SystemCri.Domain.Entities.Acceso", b =>
                {
                    b.HasOne("SystemCri.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Accesos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SystemCri.Domain.Entities.Municipio", b =>
                {
                    b.HasOne("SystemCri.Domain.Entities.Depto", "Depto")
                        .WithMany()
                        .HasForeignKey("DeptoCod")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Depto");
                });

            modelBuilder.Entity("SystemCri.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SystemCri.Domain.Entities.Depto", "Departamento")
                        .WithMany()
                        .HasForeignKey("UsuarioDepartamento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SystemCri.Domain.Entities.Municipio", "Municipio")
                        .WithMany()
                        .HasForeignKey("UsuarioMunicipio")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Departamento");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("SystemCri.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Accesos");
                });
#pragma warning restore 612, 618
        }
    }
}
