// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SystemCri.Infrastructure.Data;

#nullable disable

namespace SystemCri.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260607011836_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SystemCri.Domain.Entities.Depto", b =>
                {
                    b.Property<int>("DeptoCod")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptoCod"));

                    b.Property<string>("DeptoDescrip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeptoNom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeptoCod");

                    b.ToTable("Deptos");
                });
#pragma warning restore 612, 618
        }
    }
}
